### ISSUE TITLE
Image uploader error

### ISSUE THREAD

**Issue by phil9690** [patricklindsay/integral#22]
When I try to upload an image I get a toaster error saying 'An error occurred when uploading the image', but if I refresh the page it has been uploaded. I can keep clicking and getting the error and each time it will upload the image again. I am currently doing this in development.
<img width="1057" alt="screen shot 2017-05-19 at 15 54 04" src="https://cloud.githubusercontent.com/assets/7967282/26253441/59f7635c-3cab-11e7-93cd-6c5f0a027b25.png">

**Comment by patricklindsay** [comment]
Apologises for not getting to this sooner.

This is happening because Integral is trying to queue up image processing jobs using Delayed Jobs which hasn't been added as a dependancy.

To fix the issue in your application you will have to add Delayed Job.
```
gem 'delayed_job_active_record'
```

Run bundle then;
```
bundle exec rails generate delayed_job:active_record
bundle exec rake db:migrate
```

There are two paths to fix this issue within Integral
1. Add the dependancy into Integral, which forces everyone to use Delayed Jobs.
2. Make the Carrierwave::Backgrounder backend configurable, which is more work but allows everyone to use their background worker of choice.

**Comment by patricklindsay** [comment]
Integral requires a background jobs manager in order to process images (create different sizes, compress etc). 

The default is set to [Delayed Jobs](https://github.com/collectiveidea/delayed_job). To configure what background jobs manager is used for processing images edit the [carrierwave_backgrounder](https://github.com/lardawge/carrierwave_backgrounder) config file at `config/initializers/carrierwave_backgrounder` (which is generated when running `rails generate integral:install`
